Repository mastodon/joinmastodon, pull requests merged in 2025-04, with the labels that each got.

#881 Prettier for EVERYTHING
  CONTRIBUTING.md
  README.md
  components/Hero.tsx
  components/Layout.tsx
  components/PolicyPage.tsx
  components/SponsorCard.tsx
  data/apps.ts
  data/bio.js
  data/board.ts
  data/interviews.ts
  data/linear.json
  data/locales.js
  data/patreon.json
  data/verified.ts
  package.json
  pages/about/[slug].tsx
  pages/about/index.tsx
  pages/android/safety-standards.tsx
  pages/donor-policy/de/mastodon-ggmbh.tsx
  pages/donor-policy/mastodon-ggmbh.tsx
  pages/donor-policy/mastodon-inc.tsx
  pages/servers.tsx
  patreon.mjs
  tailwind.config.js
  utils/map.ts
Labels: enhancement

#882 Runs linting and prettier on staged files
  .gitignore
  .husky/pre-commit
  lint-staged.config.mjs
  package.json
  yarn.lock
Labels: enhancement

#859 Merch is no longer new
  components/Header.tsx
Labels: a11y-and-ux

#315 Reword apps labels
  locales/en.json
  pages/apps.tsx
  pages/verification.tsx
Labels: apps

#855 Apps: add information about openess of source code
  components/AppCard.tsx
  components/AppsGrid.tsx
  data/apps.ts
  locales/en.json
  pages/guide.tsx
Labels: enhancement
